### ISSUE TITLE
Shortcuts interfere with Sketch defaults

### ISSUE THREAD

**Issue by ErikFontanel** [pberrecloth/butter-sketch-plugin#12]
The shortcuts that come with Butter interfere with the Sketch defaults:
![image](https://user-images.githubusercontent.com/917819/29461859-8e5eaa32-842d-11e7-8686-805bb01d74db.png)
(see sketchshortcuts.com)

Unsetting shortcuts is not possible (explained here: exevil/Keys-For-Sketch#7), so you are forced to think up some bogus shortcuts and hope that some other plugin or new Sketch feature does not need define those in the future.

Personally, I opt for plugins shipping no shortcuts at all and let the user sort it out with custom shortcuts and/or Sketch Runner.

**Comment by DWilliames** [comment]
Good point. Sorry about that — I somehow completely overlooked those default shortcuts.
I'll remove the shortcuts 👍

**Comment by DWilliames** [comment]
Fixed now.
