### ISSUE TITLE
Can't butt layers from different groups

### ISSUE THREAD

**Issue by RaphyRaph** [pberrecloth/butter-sketch-plugin#17]
I'd like to be able to butt layers from different groups. I understand that usually you don't want to do that, but I also don't understand why it's not possible, and it would be very useful in some situations. Within the same artboard, the coordinate system is shared between layers. This might require a change of how positions calculated.

**Comment by DWilliames** [comment]
Thanks for this @RaphyRaph. Great insight. Not really sure why initially it was built to only handle layers in the same group — @pberrecloth can you shed any light on this?

I'll look into implementing this now.

**Comment by DWilliames** [comment]
@RaphyRaph and @pberrecloth.

I've created an implementation where you should be able to butt any layers, regardless of their parents or artboards. Can you please test it out this version for me: https://github.com/pberrecloth/butter-sketch-plugin/archive/v1.4.zip

**Comment by pberrecloth** [comment]
Works perfectly!
