### ISSUE TITLE
Autofocus Text Box is gone

### ISSUE THREAD

**Issue by HenryGillis** [pberrecloth/butter-sketch-plugin#24]
When I run butter to space layers, I have to click inside the text-box. It used to be auto-focused inside the input area. This is a minor thing, but saves me tons of time. Would be lovely if you could bring it back!

**Comment by aleksanderlazarov** [comment]
Agreed. It's not really a minor thing though - it really hurts the flow between Sketch Runner and Butter. The auto-focus made things so much faster.
Apologies for my impatience 😁
