### ISSUE TITLE
Pressing update for v1.5 doesn't update the plugin

### ISSUE THREAD

**Issue by JordanTranchina** [pberrecloth/butter-sketch-plugin#26]
<img width="632" alt="screen shot 2019-02-18 at 9 15 39 am" src="https://user-images.githubusercontent.com/41443492/52956637-c5803680-335d-11e9-9ec1-02b0da687f67.png">

Pressing this button doesn't update the plugin

**Comment by elyran2** [comment]
Finally someone wrote about it! For the last 2 days there is a constant notification in the top right corner of Sketch for "Plugin Updates" and Butter doesn't seem to want to update from 1.4 to 1.5. Drives me NUTS

**Comment by leadelazer** [comment]
same problem here, I was hoping that updating Sketch would work but still nothing happens on "Update". I think I'm going to uninstall Butter temporarily because I can't stand the constant notification 😄

**Comment by JordanTranchina** [comment]
@pberrecloth I updated the manifest to solve this issue. Opened a pull request for your review with these changes. Please review it and merge when you get the chance!
