### ISSUE TITLE
Breaks with Sketch 72 update

### ISSUE THREAD

**Issue by stephanie-walter** [pberrecloth/butter-sketch-plugin#34]
Hi,
I don't know if this is still maintained but just letting people know that the plugin doesn't work with Sketch 72.
When used with menu: nothing happens
When used with runner: the modal displays, you can enter some numbers, but nothing happens
To be fair, other plugins that relied on re-ordering layers or artboards broke with 72 (if this can help debug)

**Comment by everydayslang** [comment]
Ditto, very sad. I use this all the time.

**Comment by alexcanning** [comment]
This is one my of my essential plugins, I'll be a real shame if it's broken for good now...

**Comment by dan-burnage** [comment]
Also found this has recently broken with Sketch 72.1. Such a useful plugin, fingers crossed a fix can get implemented soon. 🤞

**Comment by rafaelevergara** [comment]
I downgraded Sketch when I realize this fundamental plugin wasn't working, looking forward to get an update soon and finally update Sketch to 72.x version 🤞 Thanks for creating such an usefull plugin, without it my workflow slow down drammatically...

**Comment by eeklipzz** [comment]
It's probably a small margarine that someone will read this and fix the plugin for us all. I butter start looking for another solution, because there's no way to know what the churn around time will be for this one. I can't believe it's not... uh... working! Ghee-se.

**Comment by dan-burnage** [comment]
Yes, let's hope someone can come to the rescue and fix this. 🤞 Whilst I don't have the expertise myself to do anything with the information, I did find the error being logged to the console in Sketch (noted below). Perhaps this is useful to someone who is more familiar with Javascript and building Sketch plugins, as my understanding is very limited in this case.

`MOJavaScriptException: TypeError: MSRect.rectWithX_y_width_height is not a function. (In 'MSRect.rectWithX_y_width_height(coords.x, coords.y, frame.size.width, frame.size.height)', 'MSRect.rectWithX_y_width_height' is undefined)`

**Comment by AidanCurrah** [comment]
I've made a quick fix for this issue here: https://gist.github.com/AidanCurrah/8422df46f4155c36a24ec3db89522e0e

If you're worried about using the fix, the change is line 245. In Sketch 72, they've changed their internal API for MSRect, which  was being used by this plugin. All I've done is replace the MSRect with a JS class which preforms a similar function to MSRect.

I've not submitted this as a PR since I'm pretty sure my fix is not the correct way to go about fixing this issue but I don't actually have access to my own copy of Sketch so I can't easily test other options. This also means I can't test the plugin properly so if you have any issues, let me know and I can have a look.

**Comment by rafaelevergara** [comment]
Thank you so much @AidanCurrah, I could finally update to Sketch 72.4 with Butter fully working. Thank you again for spending time on this fix and sharing it, have a good day!

**Comment by keno47** [comment]
@AidanCurrah You Da Man!!! - thank you.

**Comment by eeklipzz** [comment]
> I've made a quick fix for this issue here: https://gist.github.com/AidanCurrah/8422df46f4155c36a24ec3db89522e0e
> 
> If you're worried about using the fix, the change is line 245. In Sketch 72, they've changed their internal API for MSRect, which was being used by this plugin. All I've done is replace the MSRect with a JS class which preforms a similar function to MSRect.
> 
> I've not submitted this as a PR since I'm pretty sure my fix is not the correct way to go about fixing this issue but I don't actually have access to my own copy of Sketch so I can't easily test other options. This also means I can't test the plugin properly so if you have any issues, let me know and I can have a look.

Great work @AidanCurrah. There's no one butter than you!

Mac Users (not sure how PC users would do this sorry)
1. In Sketch, go to Manage Plugins 
2. Click the thin bar at the bottom of the list to Reveal Plugins Folder
3. Right-click on the butter plugin and Show Package Contents
4. Replace the butter.js file in that package with the file that @AidanCurrah made for us.

**Comment by DWilliames** [comment]
Hey all — sorry I haven't paid any attention to the Issues raised here for a long time. I don't event use Sketch on a day-to-day basis anymore.

Massive thank to @AidanCurrah for your fix. And thanks to @eeklipzz for explaining how to use the work around.
I just included Aidan's changes and created a new Release for it. So hopefully it should be really easy for anyone to get the latest update now.

Let me know if it broke anything more than it was already broken 😅
