### ISSUE TITLE
Select all layers with artboard ?

### ISSUE THREAD

**Issue by krstivoja** [pberrecloth/butter-sketch-plugin#4]
Is it possible to to take as consideration if you select artboard that all layers are selected.
Currently I have problems if some layer is locked and think this will be real time saver.

**Comment by DWilliames** [comment]
Hey @krstivoja. I know this request was quite a while ago; but I just pushed an update that does this for you.

Added some new behaviour for when less than 2 layers are selected:

* If 1 layer is selected — it will select all its sublayers (even ones that are locked). Great for selecting a single artboard or group to butt everything within it.
* If no layers are selected and there are no artboards on the current page — it will select all top level layers (even locked ones)
* If no layers are selected and there is a current artboard — it will select all the top-level layers within the artboard.
