### ISSUE TITLE
Not working in Sketch 42

### ISSUE THREAD

**Issue by ryangberry** [pberrecloth/butter-sketch-plugin#5]
Can't get this plugin to work with the new update to Sketch 42. Please help! I use Butter all the time, one of my favorite plugins. Thanks!

**Comment by helloGLD** [comment]
One of my favorites too!

**Comment by SamuelBarbosa** [comment]
I’ve tried it on sketch 45.2, not working at all too.

**Comment by Kestrel76** [comment]
Looks like the developer has set up a Kickstarter to raise funds to renew his Sketch licence, which will allow him to update this plugin.  It's here: https://www.kickstarter.com/projects/864061804/help-fund-butter-plugin

**Comment by DWilliames** [comment]
@ryangberry @helloGLD @SamuelBarbosa @Kestrel76  I am pleased to let you know that we re-wrote the plugin from the ground up and this should now all be fixed. Please raise another issue if it doesn't work for you.

**Comment by ErikFontanel** [comment]
great job guys!

**Comment by ryangberry** [comment]
🙌

**Comment by SamuelBarbosa** [comment]
Works great ! Thanks !
