### ISSUE TITLE
Support Sketch 45 plugin update system

### ISSUE THREAD

**Issue by bomberstudios** [pberrecloth/butter-sketch-plugin#6]
Hi there!

This is a quick note to remind you that Sketch 45 will include a plugin update system.

It would be awesome if you could add support to it (it's really easy!) before Sketch 45 comes out. Ideally, you should release an update for your plugin while we're still in Sketch 44, so your users will have a nice & easy experience when 45 is released.

For more details, please check http://sketchplugins.com/d/229-updating-plugins and http://developer.sketchapp.com/introduction/updating-plugins/

Thanks in advance!

**Comment by AliHammoud** [comment]
Butter stopped working in Sketch 45

**Comment by usrnk1** [comment]
It would be great to use it again 🤞

**Comment by Heilemann** [comment]
I use Butter everyday; would love to see an update to support 45.

**Comment by usrnk1** [comment]
Same here, it's an essential plugin. A massive time saver ⏱

**Comment by btothemoon** [comment]
Creators! You've obviously created a great plugin and would be nice to get it working again :)

**Comment by afiqbinary** [comment]
Hi! Great plugin you have here! Really help me a lot for my work. But it stopped working with the latest version of Sketch (45). I really hope you will update and support this plugin. Thanks!

**Comment by ShaneNZ** [comment]
Have created a PR #7 that gets it working in v45. Hopefully @pberrecloth can merge it in, although it's a bit of hack (see the PR comment :) )

**Comment by seandellis** [comment]
Until they add support, [Automate](https://github.com/Ashung/Automate-Sketch/.) has a similar feature called "Tile Objects by Position" along with tons of others. It works in Sketch 45.

**Comment by ShaneNZ** [comment]
Haven't seen that plugin, @seandellis ta - lots of good stuff in there, gonna grab it for other things. But I use the "Space Selection Up/Down/Left/Right" commands in Butter more than the "Butt Against" ones, so it doesn't scratch that itch for me but hopefully it'll help others. In any case Butter is effectively working for me from my fork/fix - if anybody wants to grab it directly while waiting for the PR here, look at https://github.com/ShaneNZ/butter-sketch-plugin

**Comment by pberrecloth** [comment]
Hello guys, Glad you like Butter.

I would like to do this properly. I no longer have a sketch licence which is why I haven't updated support. If the community is willing to help fund a Sketch licence for me I will get it updated - along with other features users have been asking for. There are many. I have always had much bigger ideas for this plugin which I'd like to get implemented.

I have started a Kickstarter, and all is explained on there. 

Help Fund Butter Plugin!
https://www.kickstarter.com/projects/864061804/help-fund-butter-plugin

Many thanks,
Peter

**Comment by stevebrown** [comment]
Hey Peter,
I hoe all is going well. Check your Kickstarter. You may be over the top now. 
Best,
Steve

**Comment by pberrecloth** [comment]
Steve, I just saw your pledge. You are a champ. Thank you! I will get this plugin rolling this week.

**Comment by stevebrown** [comment]
You're welcome. Cheers.

**Comment by chsWeb** [comment]
Also shared the KickStarter on the Sketch Together Facebook Page.

**Comment by DWilliames** [comment]
@AliHammoud @stevebrown @seandellis @ShaneNZ @afiqbinary @bmoondesign @userkamil @Heilemann I am pleased to let you all know that we re-wrote the plugin from the ground up and this should now all be fixed. Please raise another issue if it doesn't work for you.
