### ISSUE TITLE
Not working Sketch 46

### ISSUE THREAD

**Issue by chsWeb** [pberrecloth/butter-sketch-plugin#8]
Butter no longer works in Sketch 46. Butter appears in the plugin menu, but does not affect selected objects.
![butterbroeknsketch46](https://user-images.githubusercontent.com/873222/29085502-85e4e6b6-7c3d-11e7-8e15-79834215f997.gif)

**Comment by pberrecloth** [comment]
Thank you, will work on this very soon!

**Comment by DWilliames** [comment]
@chsWeb I am pleased to let you know that we re-wrote the plugin from the ground up and this should now all be fixed. Please raise another issue if it doesn't work for you.
